version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  fetch-raw-data:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          command: python3 -m src.data.fetch_raw_movie_data
          name: Fetch Raw Data
    
      - persist_to_workspace:
          root: ~/project
          paths:
              - data/*
              - models/*

  clean-movie-data:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - attach_workspace:
          at: ~/project
      - run:
          command: python3 -m src.data.make_clean_movie_data
          name: Clean Movie Data

  clean-genre-metadata:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.data.make_genre_metadata
          name: Clean Genre Data

  gen-vectorized-outcome:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.features.generate_vectorized_outcomes
          name: Generate Vectorized Outcome

  gen-count-features:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.features.generate_count_features
          name: Generate Count Features

  get-w2v-model:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: bash src/utils/get_word2vec.sh
          name: Get Word2Vec Model

  gen-w2v-features:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.features.generate_word2vec_features
          name: Generate Word2Vec Features

  test-train-split:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.utils.test_train_split
          name: Test Train Split

  train-svc:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.models.svc
          name: Train SVC

  train-naive-bayes:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.models.naive_bayes
          name: Train Naive Bayes

  train-neural-net:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.models.neural_net
          name: Train Neural Net

  score-models:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.scoring.score_models
          name: Score Models
  
  gen-comparison-report:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: bash src/report/comparison-report.sh
          name: Gen Comparison Report

  test-best-model:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python3 -m src.tests.test
          name: Test Best Model

  gen-validation-report:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: bash src/report/validate-best-report.sh
          name: Validate Best Model

workflows:
  main:
    jobs:
      - fetch-raw-data
      - clean-movie-data:
          requires:
            - fetch-raw-data