
version: 2

workflows:
  experiment-workflow:
    steps:
      -
        name: "run-pipeline-using-bash-pipeline"
        command: experiment.run_single_node
        params:
          # https://docs.paperspace.com/gradient/experiments/using-experiments/experiment-options
          command: bash src/pipeline/paperspace_bash_pipeline.sh
          container: python:3.8.6-slim-buster
          # datasetUri: "https://some_other_uri/uri"
          # datasetAwsAccessKeyId: "secret:<some_secret_name>"
          # datasetAwsSecretAccessKey: "secret:<some_other_secret_name>"
          experimentEnv:
            TMDB_API_KEY: "secret:<TMDB_API_KEY>"
          machineType: C3
          modelPath: /models #"/storage/models"
          modelType: Custom
          name: pipeline params
        checks: #[optional]
          custom:loss:
            target: "0.0..1.0"
            aggregate: "/naive_bayes/prec" #json accessor for JSON in gradient-model-metadata.json
          defaults:
            round: down #[optional, default: down, up|down]
            precision: 2 #[optional, default: 2]
            only-pulls: false #[optional, default: false]
            if-not-found: failure #[optional, default: "failure", success|failure]
            comment-on-pr: true #[optional, default: true]

    triggers:
      branches:
        only:
          - paperspace*
          - master

